linkerd:
  image: buoyantio/linkerd:1.1.2
service:
  type: NodePort
config:
    admin:
      port: 9990
    routers:
    - protocol: http
      servers:
      - ip: 0.0.0.0
        port: 4140
      interpreter:
        kind: io.l5d.namerd
        dst: /$/inet/namerd/4100
