apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: words-routes
  namespace: istio-system
spec:
  destination:
    name: words
  route:
  - labels:
      version: v1
    weight: 0
  - labels:
      version: v2
    weight: 100
